<?php

namespace Database\Seeders;

use App\Enums\PositionScope;
use App\Models\Position;
use App\Models\Rank;
use Illuminate\Database\Seeder;

class PositionAndRankSeeder extends Seeder
{
  public function run(): void
  {
    // ── Golongan / Pangkat ──
    $ranks = [
      ['name' => 'Juru Muda', 'group' => 'I/a'],
      ['name' => 'Juru Muda Tingkat I', 'group' => 'I/b'],
      ['name' => 'Juru', 'group' => 'I/c'],
      ['name' => 'Juru Tingkat I', 'group' => 'I/d'],
      ['name' => 'Pengatur Muda', 'group' => 'II/a'],
      ['name' => 'Pengatur Muda Tingkat I', 'group' => 'II/b'],
      ['name' => 'Pengatur', 'group' => 'II/c'],
      ['name' => 'Pengatur Tingkat 1', 'group' => 'II/d'],
      ['name' => 'Penata Muda', 'group' => 'III/a'],
      ['name' => 'Penata Muda Tingkat 1', 'group' => 'III/b'],
      ['name' => 'Penata', 'group' => 'III/c'],
      ['name' => 'Penata Tingkat 1', 'group' => 'III/d'],
      ['name' => 'Pembina', 'group' => 'IV/a'],
      ['name' => 'Pembina Tingkat 1', 'group' => 'IV/b'],
      ['name' => 'Pembina Utama Muda', 'group' => 'IV/c'],
      ['name' => 'Pembina Utama Madya', 'group' => 'IV/d'],
      ['name' => 'Pembina Utama', 'group' => 'IV/e'],
    ];

    foreach ($ranks as $rank) {
      Rank::updateOrCreate(['group' => $rank['group']], $rank);
    }

    // ── Jabatan ──
    // Scope menentukan batas jumlah pemangku jabatan:
    //   SYSTEM     => hanya satu di seluruh sistem (mis. Walikota, Sekda)
    //   DEPARTMENT => hanya satu per OPD / unit kerja (mis. Kepala Dinas, Camat)
    //   NONE       => boleh banyak (mis. Staf, Fungsional Umum)
    $positions = [
      ['name' => 'Walikota', 'scope' => PositionScope::SYSTEM],
      ['name' => 'Wakil Walikota', 'scope' => PositionScope::SYSTEM],
      ['name' => 'Sekretaris Daerah', 'scope' => PositionScope::SYSTEM],
      ['name' => 'Asisten Pemerintahan dan Kesejahteraan Rakyat', 'scope' => PositionScope::SYSTEM],
      ['name' => 'Asisten Administrasi Umum', 'scope' => PositionScope::SYSTEM],
      ['name' => 'Asisten Perekonomian dan Pembangunan', 'scope' => PositionScope::SYSTEM],
      ['name' => 'Staf Ahli', 'scope' => PositionScope::NONE],
      ['name' => 'Kepala Dinas', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Sekretaris Dinas', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Kepala Bagian', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Kepala Bidang', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Kepala Seksi', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Kepala Sub Bagian', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Camat', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Sekretaris Camat', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Lurah', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Sekretaris Lurah', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Kepala Puskesmas', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Kepala Badan', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Inspektur', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Sekretaris Inspektur', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Sekretaris Dewan', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Staf', 'scope' => PositionScope::NONE],
      ['name' => 'Fungsional Umum', 'scope' => PositionScope::NONE],
      ['name' => 'Analis Kebijakan', 'scope' => PositionScope::NONE],
      ['name' => 'Pranata Komputer', 'scope' => PositionScope::NONE],
      ['name' => 'Auditor', 'scope' => PositionScope::NONE],
      ['name' => 'Bendahara Pengeluaran', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Bendahara Penerimaan', 'scope' => PositionScope::DEPARTMENT],
      ['name' => 'Bendahara Pembantu', 'scope' => PositionScope::NONE],
    ];

    foreach ($positions as $pos) {
      Position::updateOrCreate(
        ['name' => $pos['name']],
        ['uniqueness_scope' => $pos['scope']],
      );
    }

    // ── Jabatan lengkap Pemerintah Kota ──
    // Daftar nominatif jabatan struktural & fungsional di lingkup Pemkot.
    // Scope ditentukan otomatis berdasarkan pola nama jabatan.
    $jabatanPemkot = [
      'Asisten Administrasi Umum',
      'Asisten Administrasi Pembangunan',
      'Asisten Pemerintahan dan Kesra',
      'Camat',
      'Sekretaris Camat',
      'Lurah',
      'Sekretaris Kelurahan',
      'Kepala Badan Kepegawaian dan Pengembangan SDM',
      'Kepala Badan Pengelola Keuangan dan Aset Daerah',
      'Kepala Badan Pengelola Pajak dan Retribusi Daerah',
      'Kepala Badan Kesatuan Bangsa dan Politik',
      'Kepala Dinas Pendidikan Kepemudaan dan Olahraga',
      'Kepala Dinas Kesehatan',
      'Kepala Dinas Pekerjaan Umum dan Penataan Ruang',
      'Kepala Dinas Sosial',
      'Kepala Dinas Pangan',
      'Kepala Dinas Pertanian',
      'Kepala Dinas Perikanan',
      'Kepala Dinas Perhubungan',
      'Kepala Dinas Perdagangan, Koperasi dan UKM',
      'Kepala Dinas Tenaga Kerja dan Perindustrian',
      'Kepala Dinas Lingkungan Hidup dan Kehutanan',
      'Kepala Dinas Kependudukan dan Pencatatan Sipil',
      'Kepala Dinas Pengendalian Penduduk dan Keluarga Berencana',
      'Kepala Dinas Pemberdayaan Perempuan Dan Perlindungan Anak',
      'Kepala Dinas Kebakaran',
      'Kepala Dinas Perpustakaan dan Kearsipan',
      'Kepala Dinas Komunikasi dan Informatika',
      'Kepala Pelaksana BPBD',
      'Kepala Satuan Polisi Pamong Praja',
      'Direktur RSUD',
      'Kepala Bagian Hukum',
      'Kepala Bagian Organisasi',
      'Kepala Bagian Kesejahteraan Rakyat',
      'Kepala Bagian Perekonomian dan Usaha Daerah',
      'Kepala Bagian Administrasi Pembangunan',
      'Kepala Bagian Sumber Daya Alam',
      'Kepala Bagian Umum dan Perlengkapan',
      'Kepala Bagian Pengadaan Barang dan Jasa',
      'Kepala Bagian Protokol dan Komunikasi Pimpinan',
      'Kepala UPTD Puskesmas',
      'Kepala UPTD Rumah Potong Hewan',
      'Kepala UPTD Terminal',
      'Kepala UPTD Kebun Raya',
      'Kepala UPTD Tempat Pelelangan Ikan',
      'Kepala UPTD Sistem Pengelolaan Air Limbah Domestik',
      'Kepala UPTD Rumah Susun',
      'Kepala Bidang Bina Marga',
      'Kepala Bidang Cipta Karya',
      'Kepala Bidang Sumber Daya Air',
      'Kepala Bidang Penataan Ruang',
      'Kepala Bidang Perumahan dan Kawasan Permukiman',
      'Kepala Bidang Anggaran',
      'Kepala Bidang Perbendaharaan dan Kas Daerah',
      'Kepala Bidang Akuntansi dan Pelaporan',
      'Kepala Bidang Aset Daerah',
      'Kepala Bidang Koperasi',
      'Kepala Bidang Pemberdayaan UKM',
      'Kepala Bidang Perdagangan',
      'Kepala Bidang Metrologi',
      'Kepala Bidang Kesehatan Masyarakat',
      'Kepala Bidang Pelayanan Kesehatan',
      'Kepala Bidang Sumber Daya Kesehatan',
      'Kepala Bidang Pencegahan dan Pengendalian Penyakit',
      'Kepala Bidang Kedaruratan dan Logistik',
      'Kepala Bidang Pencegahan dan Kesiapsiagaan',
      'Kepala Bidang Rehabilitasi dan Rekonstruksi',
      'Kepala Bidang Pembinaan Pendidikan Dasar',
      'Kepala Bidang Pembinaan PAUD dan PNF',
      'Kepala Bidang Ketenagaan dan Pengembangan SDM',
      'Kepala Bidang Mutasi dan Promosi',
      'Kepala Bidang Pengembangan Kompetensi Aparatur',
      'Kepala Bidang Penilaian Kinerja Aparatur dan Penghargaan',
      'Kepala Bidang Ideologi Wawasan Kebangsaan dan Karakter Bangsa',
      'Kepala Bidang Politik Dalam Negeri',
      'Kepala Bidang Kewaspadaan Nasional dan Penanganan Konflik',
      'Kepala Bidang Ketahanan Ekonomi, Sosial, Budaya, Agama dan Ormas',
      'Kepala Bidang Perlindungan Masyarakat',
      'Kepala Bidang Penegakan Peraturan Daerah',
      'Kepala Bidang Ketertiban Umum dan Ketentraman Masyarakat',
      'Kepala Bidang Keolahragaan',
      'Kepala Bidang Pengembangan Pemuda',
      'Kepala Bidang Pemberdayaan Pemuda',
      'Kepala Bidang Pemasaran Pariwisata',
      'Kepala Bidang Destinasi dan Industri Pariwisata',
      'Kepala Bidang Ekonomi Kreatif',
      'Kepala Bidang Hubungan Industrial dan Jaminan Sosial',
      'Kepala Bidang Penempatan dan Pelatihan Tenaga Kerja',
      'Kepala Bidang Pelayanan Pendaftaran Penduduk',
      'Kepala Bidang Pemanfaatan Data dan Inovasi',
      'Kepala Bidang Pengelolaan Informasi Administrasi Kependudukan',
      'Kepala Bidang Keluarga Berencana',
      'Kepala Bidang Ketahanan dan Kesejahteraan Keluarga',
      'Kepala Bidang Pengendalian Penduduk, Penyuluhan dan Penggerakan',
      'Kepala Bidang Pelembagaan PUG dan Pemberdayaan Perempuan',
      'Kepala Bidang Kualitas Hidup Perempuan',
      'Kepala Bidang Perlindungan Khusus Anak',
      'Kepala Bidang Pemenuhan Hak Anak',
      'Kepala Bidang Layanan Perlindungan Perempuan dan Anak',
      'Kepala Bidang Rehabilitasi Sosial',
      'Kepala Bidang Perlindungan dan Jaminan Sosial',
      'Kepala Bidang Penanganan Fakir Miskin',
      'Kepala Bidang Pemberdayaan Sosial',
      'Kepala Bidang Kebersihan',
      'Kepala Bidang Persampahan dan Limbah B3',
      'Kepala Bidang Peningkatan Kapasitas dan Pemantauan Lingkungan',
      'Kepala Bidang Tata Lingkungan',
      'Kepala Bidang Perikanan Tangkap',
      'Kepala Bidang Perikanan Budidaya',
      'Kepala Bidang Perizinan, Pembinaan Mutu dan Pengelolaan TPI',
      'Kepala Bidang Pemberdayaan dan Kelembagaan Usaha Perikanan',
      'Kepala Bidang Tanaman Pangan',
      'Kepala Bidang Perkebunan dan Hortikultura',
      'Kepala Bidang Peternakan dan Kesehatan Heawan',
      'Kepala Bidang Prasarana, Sarana dan Penyuluhan',
      'Kepala Bidang Distribusi dan Cadangan Pangan',
      'Kepala Bidang Konsumsi dan Keamanan Pangan',
      'Kepala Bidang Teknologi Informasi Komunikasi dan Persandian',
      'Kepala Bidang Informasi dan Komunikasi Publik',
      'Kepala Bidang Penyelenggaraan E-Government',
      'Kepala Sub Bagian Perencanaan, Keuangan dan Pelaporan',
      'Kepala Sub Bagian Umum dan Kepegawaian',
      'Kepala Sub Bagian Protokol dan Perjalanan Dinas',
      'Kepala Sub Bagian Rumah Tangga dan Perlengkapan',
      'Kepala Sub Bagian Pembinaan BUMD dan BLUD',
      'Kepala Sub Bagian Layanan Pengadaan Secara Elektronik',
      'Kepala Sub Bidang Pengadaan dan Pemberhentian',
      'Kepala Sub Bidang Mutasi dan Promosi',
      'Kepala Sub Bidang Kepangkatan',
      'Kepala Sub Bidang Pengembangan Kompetensi',
      'Kepala Sub Bidang Disiplin dan Penghargaan',
      'Kepala Sub Bidang Anggaran',
      'Kepala Sub Bidang Perbendaharaan',
      'Kepala Sub Bidang Kas Daerah',
      'Kepala Sub Bidang Tata Kelola Aset',
      'Kepala Sub Bidang Perencanaan Aset',
      'Kepala Sub Bidang Penatausahaan dan Pelaporan Aset',
      'Kepala Sub Bidang Pendaftaran dan Pendataan Pajak',
      'Kepala Sub Bidang Penetapan dan Keberatan',
      'Kepala Sub Bidang Penagihan, Verifikasi dan Pelaporan',
      'Kepala Sub Bidang Pemerintahan',
      'Kepala Sub Bidang Kelembagaan',
      'Kepala Sub Bidang Litbang',
      'Kepala Seksi Pemerintahan dan Pelayanan Publik',
      'Kepala Seksi Ketentraman dan Ketertiban Umum',
      'Kepala Seksi Pembangunan dan Pemberdayaan Masyarakat',
      'Kepala Seksi Kurikulum dan Penilaian',
      'Kepala Seksi Peserta Didik dan Pembangunan Karakter',
      'Kepala Seksi Kelembagaan dan Sarana Prasarana',
      'Kepala Seksi Pendidik dan Tenaga Kependidikan',
      'Kepala Seksi Kesehatan Keluarga dan Gizi',
      'Kepala Seksi Pelayanan Kesehatan Primer',
      'Kepala Seksi Pelayanan Kesehatan Rujukan',
      'Kepala Seksi Promosi Kesehatan dan Pemberdayaan Masyarakat',
      'Kepala Seksi Kefarmasian, Alat Kesehatan dan PKRT',
      'Kepala Seksi Surveilans dan Imunisai',
      'Kepala Seksi Pencegahan dan Pengendalian Penyakit Menular',
      'Kepala Seksi Pencegahan dan Pengendalian Penyakit Tidak Menular',
      'Kepala Seksi Sarana Prasarana Darurat dan Logistik',
      'Kepala Seksi Rencana Operasi Penyelamatan',
      'Kepala Seksi Rencana Operasi Pemadaman',
      'Kepala Seksi Inspeksi Proteksi Kebakaran',
      'Kepala Seksi Komunikasi Operasi dan Investigasi',
      'Kepala Seksi Manajemen Rekayasa Lalu Lintas',
      'Kepala Seksi Pengendalian Operasional LLAJ',
      'Kepala Seksi Angkutan Darat',
      'Kepala Seksi Angkutan Laut dan Kepelabuhanan',
      'Kepala Seksi Sarana Teknik',
      'Kepala Seksi Pendaftaran Penduduk',
      'Kepala Seksi Registrasi dan Pencatatan Sipil',
      'Kepala Seksi Perkawinan dan Perceraian',
      'Kepala Seksi Pemanfaatan Data dan Dokumen Kependudukan',
      'Kepala Seksi Pengelolaan Media dan Informasi Publik',
      'Kepala Seksi Layanan TIK dan Keamanan Informasi',
      'Kepala Seksi Pengembangan Ekosistem E-Government',
      'Kepala Seksi Tata Kelola E-Government',
      'Kepala Seksi Persandian',
      'Kepala Seksi Pengaduan Masyarakat',
      'Kepala Seksi Pelayanan Penanaman Modal',
      'Kepala Seksi Pengelolaan Izin dan Non Izin',
      'Kepala Seksi Pengembangan Iklim Investasi',
      'Kepala Seksi Pemberdayaan Pemuda',
      'Kepasi Seksi Peningkatan Prestasi Olahraga',
      'Kepala Seksi Promosi dan Kerja Sama',
      'Kepala Seksi Pengembangan Destinasi Pariwisata',
      'Kepala Seksi Pengembangan Usaha Koperasi',
      'Kepala Seksi Pembinaan dan Pengembangan UKM',
      'Kepala Seksi Pengawasan Perdagangan',
      'Kepala Seksi Pelayanan Tera dan Tera Ulang',
      'Kepala Seksi Pembangunan Industri Kecil dan Menengah',
      'Kepala Seksi Pengembangan Teknologi Industri',
      'Kepala Seksi Perlindungan Perempuan dan Anak',
      'Kepala Seksi Data dan Informasi Gender dan Anak',
      'Kepala Seksi Pemenuhan Hak Anak',
      'Kepala Seksi Rehabilitasi Sosial Anak dan Lansia',
      'Kepala Seksi Jaminan Sosial Keluarga',
      'Kepala Seksi Perlindungan Sosial Korban Bencana',
      'Kepala Seksi Kebersihan Jalan dan Lingkungan',
      'Kepala Seksi Kebersihan Teluk, Pesisir, dan Kali',
      'Kepala Seksi Pengelolaan TPA',
      'Kepala Seksi Pengurangan Sampah dan Limbah B3',
      'Kepala Seksi Kajian Dampak Lingkungan Hidup',
      'Kepala Seksi Pemantauan Pencemaran dan Kerusakan Lingkungan',
      'Kepala Seksi Penaatan Hukum Lingkungan',
      'Kepala Seksi Perencanaan Tata Ruang dan Pemetaan',
      'Kepala Seksi Pengendalian dan Kelayakan Ruang',
      'Kepala Seksi Irigasi',
      'Kepala Seksi Air Tanah dan Air Baku',
      'Kepala Seksi Pengembangan Air Bersih',
      'Kepala Seksi Penanganan Sungai dan Tebing',
      'Kepala Seksi Perencanaan dan Leger Jalan',
      'Kepala Seksi Pembangunan Jalan dan Jembatan',
      'Kepala Seksi Peralatan dan Sarana Teknis',
      'Kepala Seksi Perizinan dan Pencatatan Usaha Perikanan',
      'Kepala Seksi Produksi dan Sarana Prasarana Budidaya',
      'Kepala Seksi Pembinaan Mutu dan Pemasaran Hasil Perikanan',
      'Kepala Seksi Pengelolaan dan Penyelenggaraan TPI',
      'Kepala Seksi Produksi dan Perbenihan',
      'Kepala Seksi Keamanan Pangan',
      'Kepala Seksi Kerawanan Pangan',
      'Kepala Seksi Kesehatan Hewan, Pengolahan dan Pemasaran',
      'Kepala Seksi Perbibitan dan Produksi Peternakan',
      'Kepala Seksi Pengawasan Hewan, Obat dan Pakan',
      'Kepala Seksi Kelembagaan, Ketenagaan, Metode dan Informasi',
      'Analis Kebijakan Ahli Madya',
      'Analis Kebijakan Ahli Muda',
      'Analis Kebijakan Ahli Pertama',
      'Analis SDM Aparatur',
      'Analis Perencanaan, Evaluasi dan Pelaporan',
      'Analis Keuangan Pusat dan Daerah',
      'Analis Ketahanan Pangan',
      'Analis Ketahanan Keluarga',
      'Analis Kebencanaan',
      'Analis Hukum',
      'Analis Statistik',
      'Analis Tata Ruang',
      'Analis Jalan dan Jembatan',
      'Analis Sistem Informasi dan Jaringan',
      'Pranata Komputer',
      'Pranata Hubungan Masyarakat',
      'Perancang Peraturan Perundang-undangan',
      'Fungsional Perencana',
      'Fungsional Auditor',
      'Fungsional Pengawas Penyelenggaraan Urusan Pemerintahan Daerah',
      'Penyuluh Sosial',
      'Pekerja Sosial',
      'Pamong Budaya',
      'Pustakawan',
      'Arsiparis',
      'Penyuluh Pertanian',
      'Penyuluh Perikanan',
      'Penyuluh Keluarga Berencana',
      'Penyuluh Kesehatan Masyarakat',
      'Dokter Ahli Madya',
      'Dokter Ahli Muda',
      'Dokter Ahli Pertama',
      'Dokter Spesialis',
      'Dokter Gigi',
      'Apoteker',
      'Asisten Apoteker',
      'Perawat',
      'Bidan',
      'Sanitarian',
      'Nutrisionis',
      'Epidemiolog Kesehatan',
      'Pranata Laboratorium Kesehatan',
      'Fisioterapis',
      'Perekam Medis',
      'Administrator Kesehatan',
      'Polisi Pamong Praja',
      'Polisi Kehutanan',
      'Pranata Penyelamatan Kebakaran',
      'Pemeriksa dan Penguji Proteksi Alat Kebakaran',
      'Pengawas Sekolah',
      'Pamong Belajar',
      'Penilik',
      'Guru Pembina',
      'Guru Madya',
      'Guru Muda',
      'Guru Pertama',
      'Bendahara Pengeluaran',
      'Bendahara Penerimaan',
      'Bendahara Gaji',
      'Bendahara Barang',
      'Pengurus Barang Milik Daerah',
      'Pengelola Kepegawaian',
      'Pengelola Keuangan',
      'Pengelola Laporan Keuangan',
      'Pengadministrasi Umum',
      'Pengadministrasi Kepegawaian',
      'Pengadministrasi Keuangan',
      'Pengadministrasi Barang',
      'Operator SIAK',
      'Operator SIMDA',
      'Pelaksana',
    ];

    // Jabatan struktural eselon yang hanya satu pemangku per OPD/unit kerja.
    $departmentJabatan = [
      'Camat',
      'Sekretaris Camat',
      'Lurah',
      'Sekretaris Kelurahan',
      'Inspektur Kota',
      'Direktur RSUD',
    ];

    // Nama jabatan yang sudah didefinisikan di atas — dilewati agar tanpa duplikat
    // dan tidak menimpa scope yang sudah ditetapkan.
    $existingNames = array_column($positions, 'name');

    foreach ($jabatanPemkot as $name) {
      if (in_array($name, $existingNames, true)) {
        continue;
      }

      $scope = match (true) {
        str_starts_with($name, 'Asisten ') && ! str_starts_with($name, 'Asisten Apoteker') => PositionScope::SYSTEM,
        str_starts_with($name, 'Kepala ') || str_starts_with($name, 'Kepasi ') => PositionScope::DEPARTMENT,
        in_array($name, $departmentJabatan, true) => PositionScope::DEPARTMENT,
        default => PositionScope::NONE,
      };

      Position::updateOrCreate(
        ['name' => $name],
        ['uniqueness_scope' => $scope],
      );
    }
  }
}
