services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: sppd_update_app
    restart: unless-stopped
    ports:
      - "8004:8000"
    depends_on:
      - db
    command: >
      sh -c "
        mkdir -p /app/storage/app/private /app/storage/app/public &&
        chown -R www-data:www-data /app/storage &&
        chmod -R 775 /app/storage &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    networks:
      - app_net
    volumes:
      - ./storage/app:/app/storage/app
      - .env:/app/.env
      - ./docker/php.ini:/usr/local/etc/php/conf.d/uploads.ini

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: sppd_update_queue
    restart: unless-stopped
    depends_on:
      - db
    command: >
      sh -c "
        php artisan queue:work --verbose --tries=3 --sleep=3 --timeout=120
      "
    networks:
      - app_net
    volumes:
      - ./storage/app:/app/storage/app
      - .env:/app/.env
      - ./docker/php.ini:/usr/local/etc/php/conf.d/uploads.ini

  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: sppd_update_scheduler
    restart: unless-stopped
    depends_on:
      - db
    command: >
      sh -c "
        php artisan schedule:work
      "
    networks:
      - app_net
    volumes:
      - ./storage/app:/app/storage/app
      - .env:/app/.env
      - ./docker/php.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:8.0
    container_name: sppd_update_mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_sppd_update
      MYSQL_ROOT_PASSWORD: icangg05@2002
      MYSQL_USER: user
      MYSQL_PASSWORD: icangg05@2002
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: sppd_update_phpmyadmin
    ports:
      - "8084:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - app_net

networks:
  app_net:

volumes:
  dbdata:
